using System.Collections.Generic;
using DotNetHelpers.Sample.Models;

namespace DotNetHelpers.Sample.Factories
{
    public static class ProductsFactory
    {
        #region Properties
        public static List<Product> Products => new List<Product>
        {
            //new Product{Id = 1,Caption = "კვების ბლოკი - S-120-12", Price = 30, Quantity =262},
            //new Product{Id = 2,Caption = "კვების ბლოკი - Power Spply", Price = 12, Quantity =1},
            //new Product{Id = 3,Caption = "კვების ბლოკი - Power Spply S-40-12 ", Price = 15, Quantity =160},
            new Product{Id = 4,Caption = "კვების ბლოკი - Power Spply", Price = 25, Quantity =260},
            new Product{Id = 5,Caption = "კვების ბლოკი - S-180-12", Price = 50, Quantity =135},
            new Product{Id = 6,Caption = "კვების ბლოკი -  S-250-12", Price = 60, Quantity =84},
            new Product{Id = 7,Caption = "კვების ბლოკი - S-360-12", Price = 80, Quantity =62},
            new Product{Id = 8,Caption = "კვების ბლოკი - Power Spply", Price = 30, Quantity =1},
            new Product{Id = 9,Caption = "კვების ბლოკი - S-240-24", Price = 50, Quantity =98},
            new Product{Id = 10,Caption = "კვების ბლოკი -  S-480-24", Price = 95, Quantity =37},
            new Product{Id = 11,Caption = "კვების ბლოკი - Power Spply", Price = 145, Quantity =16},
            new Product{Id = 12,Caption = "კვების ბლოკი - Power Spply", Price = 45, Quantity =1},
            new Product{Id = 13,Caption = "კვების ბლოკი - Power Spply", Price = 65, Quantity =1},
            new Product{Id = 14,Caption = "კვების ბლოკი - Power Spply", Price = 145, Quantity =1},
            new Product{Id = 15,Caption = "კვების ბლოკი - Power Spply", Price = 110, Quantity =1},
            new Product{Id = 16,Caption = "Power Spply", Price = 145, Quantity =1},
            new Product{Id = 17,Caption = "2.0 MP კამერა - AHD IR WATERPROOF CAMERA MAV-643B2", Price = 57, Quantity =133},
            new Product{Id = 18,Caption = "მყარი დისკი  1TB -  Seagate SkyHawk ST1000VX005 1TB", Price = 130, Quantity =97},
            new Product{Id = 19,Caption = "მყარი დისკი  2TB - Seagate SkyHawk ST2000VX008 2TB", Price = 210, Quantity =120},
            new Product{Id = 20,Caption = "მყარი დისკი  4TB - Seagate SkyHawk ST4000VX007 4TB 3.5", Price = 360, Quantity =60},
            new Product{Id = 21,Caption = "როუტერი - JCG JHR-N916R", Price = 45, Quantity =950},
            new Product{Id = 22,Caption = "როუტერი - JCG JHR-N926R", Price = 50, Quantity =465},
            new Product{Id = 23,Caption = "როუტერი - JHR-N835R", Price = 85, Quantity =230},
            new Product{Id = 24,Caption = "ანდროიდ ტვ ბოქსი - MXQ PRO 4K TV Box", Price = 100, Quantity =1},
            new Product{Id = 25,Caption = "ანდროიდ ტვ ბოქსი X96 Mini", Price = 100, Quantity =12},
            new Product{Id = 26,Caption = " დომოფონი - WI-FI VIDEO DOOR PHONE 9 INCH", Price = 800, Quantity =1},
            new Product{Id = 27,Caption = " დომოფონი - WI-FI VIDEO DOOR PHONE 7 INCH", Price = 700, Quantity =3},
            new Product{Id = 28,Caption = "დომოფონი - DOOR PHONE 7 INCH", Price = 450, Quantity =5},
            new Product{Id = 29,Caption = "კვების ბლოკი - MSP-C1500IC12.0-18W-DE", Price = 6, Quantity =1},
            new Product{Id = 30,Caption = "კვების ბლოკი - WA-12J12FG", Price = 5, Quantity =100},
            new Product{Id = 31,Caption = "კვების ბლოკი - NU30-4120250-I3 AC", Price = 13, Quantity =1},
            new Product{Id = 32,Caption = "კვების ბლოკი - NU36-4120300-I3", Price = 15, Quantity =1},
            new Product{Id = 33,Caption = "კვების ბლოკი - ADA017", Price = 20, Quantity =5},
            new Product{Id = 34,Caption = "DVR ჩამწერი - MAR-1014E DX", Price = 150, Quantity =31},
            new Product{Id = 35,Caption = "DVR ჩამწერი - MAR-1018E DX", Price = 210, Quantity =35},
            new Product{Id = 36,Caption = "DVR ჩამწერი - MAR-1016E DX ", Price = 400, Quantity =44},
            new Product{Id = 37,Caption = "DVR ჩამწერი -MAR-2304EX DX ", Price = 300, Quantity =17},
            new Product{Id = 38,Caption = "DVR ჩამწერი - MAR-2308E X  DX ", Price = 400, Quantity =15},
            new Product{Id = 39,Caption = "DVR ჩამწერი - MAR-2316E X DX ", Price = 720, Quantity =18},
            new Product{Id = 40,Caption = "მაგნიტური კარის საკეტი - C KEY 01 E", Price = 60, Quantity =1},
            new Product{Id = 41,Caption = "მაგნიტური კარის საკეტი - C KEY02M", Price = 60, Quantity =1},
            new Product{Id = 42,Caption = "მაგნიტური კარის საკეტი - C KEY03M", Price = 60, Quantity =1},
            new Product{Id = 43,Caption = "მაგნიტური კარის საკეტი - ELECTRIC BOLT LOCK", Price = 0, Quantity =1},
            new Product{Id = 44,Caption = "გარე გამოყენების კამერა 2.0MP სონის ლინზით - MAV-86305 DX", Price = 100, Quantity =50},
            new Product{Id = 45,Caption = "4.0MP კამერა - MAV-92305 DX", Price = 140, Quantity =80},
            new Product{Id = 46,Caption = "2.0MP შიდა კამერა - MAV-642F2/K ", Price = 47, Quantity =0},
            new Product{Id = 47,Caption = "2.0MP შიდა კამერა - MAV-862F2/K DX", Price = 80, Quantity =44},
            new Product{Id = 48,Caption = "4.0MP შიდა კამერა - MAV-922F3/K DX ", Price = 120, Quantity =1},
            new Product{Id = 49,Caption = "გარე კამერა რკინის კორპუსით - MAV-863W1 DX", Price = 145, Quantity =1},
            new Product{Id = 50,Caption = "მინი კამერა - MINI CAMERA 1,3MP", Price = 80, Quantity =24},
            new Product{Id = 51,Caption = "კონექტორი - RJ-45 Modular Cord Coupler", Price = 1, Quantity =1},
            new Product{Id = 52,Caption = "სახანძრო კაბელი", Price = 95, Quantity =10},
            new Product{Id = 53,Caption = "კაბელები ქსელის", Price = 152.5m, Quantity =10},
            new Product{Id = 54,Caption = "კოაქსიალური კაბელი", Price = 40, Quantity =10},
            new Product{Id = 55,Caption = "CCTV კაბელი", Price = 85, Quantity =10},
            new Product{Id = 56,Caption = "ანალოგიური კამერა - MAV-912F3/K", Price = 100, Quantity =5},
            new Product{Id = 57,Caption = "კვების ბლოკი - S-600-12", Price = 130, Quantity =16},
            new Product{Id = 58,Caption = "მინი - ფარული კამერა MINI CAMERA 2MP", Price = 100, Quantity =14},
            new Product{Id = 59,Caption = "მინი - ფარული კამერა ", Price = 110, Quantity =5},
            new Product{Id = 60,Caption = "სამსუნგის დომოფონი - Door phone  samsung", Price = 350, Quantity =9},
            new Product{Id = 61,Caption = "მყარი დისკი Seagate SkyHawk ST3000VX010 3TB 3.5", Price = 270, Quantity =120},
            new Product{Id = 62,Caption = "საჰაერო მაუსი კლავიატურით ", Price = 35, Quantity =20},
            new Product{Id = 63,Caption = "უკაბელო კლავიატურა - AIR MOUSE CI8", Price = 25, Quantity =49},
            new Product{Id = 64,Caption = "ვიდეო ადაპტერი - EASY CAPTURE", Price = 25, Quantity =5},
            new Product{Id = 65,Caption = "ადაპტერი - POE CPO48V", Price = 13, Quantity =21},
            new Product{Id = 66,Caption = "ადაპტერი POE CPO24V", Price = 13, Quantity =20},
            new Product{Id = 67,Caption = "მაგნიტური კარის საკეტი CREAD01", Price = 45, Quantity =10},
            new Product{Id = 68,Caption = "კოდური კარის საკეტი CREAD02M", Price = 100, Quantity =5},
            new Product{Id = 69,Caption = "წყალგაუმტარი ადაპტერი C1CH3A", Price = 17, Quantity =48},
            new Product{Id = 70,Caption = "წყალგაუმტარი ადაპტერი C1CH2A", Price = 13, Quantity =49},
            new Product{Id = 71,Caption = "მინი სპლიტერი VGA2 HDMI CVH01", Price = 21, Quantity =13},
            new Product{Id = 72,Caption = " მინი სპლიტერი - HDMI2AV RH_01", Price = 29, Quantity =3},
            new Product{Id = 73,Caption = "ადაპტერი - HDMI TO VGA ADAPTER VGA02", Price = 17, Quantity =17},
            new Product{Id = 74,Caption = "მინი სპლიტერი - HDMI2VGA CHV02", Price = 21, Quantity =14},
            new Product{Id = 75,Caption = "მინი სპლიტერი - AV2HDMI RH_01", Price = 29, Quantity =3},
            new Product{Id = 76,Caption = "სპლიტერი 2 იანი CHT30011G1", Price = 2, Quantity =100},
            new Product{Id = 77,Caption = "სპლიტერი 4 იანი HC2001020A", Price = 3.5m, Quantity =100},
            new Product{Id = 78,Caption = "სპლიტერი 8 იანი HC200180", Price = 6, Quantity =100},
            new Product{Id = 79,Caption = "გადამცემი BL02", Price = 6, Quantity =50},
            new Product{Id = 80,Caption = "ერთ არხიანი გადამცემი BL 01", Price = 8, Quantity =50},
            new Product{Id = 81,Caption = "გადამყვანი კაბელი", Price = 1, Quantity =50},
            new Product{Id = 82,Caption = "BNC კონექტორი 0.5m", Price = 3, Quantity =50},
            new Product{Id = 83,Caption = "BNC კონექტორი 1m", Price = 3, Quantity =50},
            new Product{Id = 84,Caption = "RCA კონექტორი", Price = 1, Quantity =50},
            new Product{Id = 85,Caption = "კონექტორი 300100FM", Price = 1, Quantity =50},
            new Product{Id = 86,Caption = "კონექტორი 20083", Price = 1, Quantity =50},
            new Product{Id = 87,Caption = "კონექტორი 20082", Price = 1, Quantity =50},
            new Product{Id = 88,Caption = "კონექტორი 20081C", Price = 1, Quantity =50},
            new Product{Id = 89,Caption = "კომპლექტაცია 4 გარე კამერა", Price = 360, Quantity =38},
            new Product{Id = 90,Caption = "ნაკრები (4 შიდა და 4 გარე კამერა) ", Price = 570, Quantity =39},
            new Product{Id = 91,Caption = "უნივერსალური პულტი", Price = 15, Quantity =100},
            new Product{Id = 92,Caption = "კამერის გარე კაბელი", Price = 90, Quantity =10},
            new Product{Id = 93,Caption = "პირბადე KN95", Price = 10, Quantity =1000}
        };
        #endregion
    }
}
